# Generated by Django 5.0.7 on 2024-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fisherman',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
