# Generated by Django 5.0.7 on 2024-07-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_fish_alter_fisherman_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('catcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fisherman')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.fish')),
            ],
        ),
    ]
