# Generated by Django 5.0.7 on 2024-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_catch'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisherman',
            name='advance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fisherman',
            name='income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
