# Generated by Django 5.0.7 on 2024-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_fisherman_advance_fisherman_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
