# Generated by Django 5.0.7 on 2024-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_fish_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='paid',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catch',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
