# Generated by Django 5.0.7 on 2024-07-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_catch_paid_catch_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidByManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('catchesPaid', models.ManyToManyField(to='myApp.catch')),
                ('fisherMan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.fisherman')),
            ],
        ),
    ]
