# Generated by Django 5.0.8 on 2024-08-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_paidbymanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='date',
            new_name='catch_date',
        ),
        migrations.RenameField(
            model_name='catch',
            old_name='catcher',
            new_name='fisherman',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='income',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='phoneNo',
        ),
        migrations.AddField(
            model_name='catch',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catch',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fisherman',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fisherman',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catch',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fish'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('date_requested', models.DateField()),
                ('is_repaid', models.BooleanField(default=False)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fisherman')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('Catch', 'Catch'), ('Advance', 'Advance')], max_length=10)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fisherman')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('log_description', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.payment')),
            ],
        ),
        migrations.DeleteModel(
            name='PaidByManager',
        ),
    ]
