# Generated by Django 5.0.8 on 2024-08-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_date_catch_catch_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance',
            name='is_repaid',
        ),
    ]
