# Generated by Django 5.0.8 on 2024-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_advance_is_repaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='royalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
    ]
