# Generated by Django 5.0.8 on 2024-08-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_fish_royalty_amount_delete_paymentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyFisherman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(max_length=50)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.royaltyfisherman')),
            ],
        ),
        migrations.CreateModel(
            name='CatchRoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catch_date', models.DateField()),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fish')),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.royaltyfisherman')),
            ],
        ),
    ]
