# Generated by Django 5.0.8 on 2024-08-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_royaltyfisherman_paymentroyalty_catchroyalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentroyalty',
            name='payment_type',
        ),
    ]
