# Generated by Django 5.0.8 on 2024-08-28 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_manager_payment_manager_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.manager'),
        ),
        migrations.AddField(
            model_name='paymentroyaltyrecived',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.manager'),
        ),
    ]
