# Generated by Django 5.0.8 on 2024-08-30 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_rename_paymentroyaltyrecived_paymentroyaltyreceived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_on', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True, null=True)),
                ('date_spent', models.DateField(default=django.utils.timezone.now)),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
